# Generated by Django 5.0.1 on 2024-02-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_supervisor_notes_user_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='super_id',
            new_name='supervisor',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Progress',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Task_details',
            new_name='task_details',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Projectname',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='super_id',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='super_id',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='Task_heading',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_heading',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
