# Generated by Django 5.0.1 on 2024-02-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tasks_progress_alter_tasks_task_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
