# Generated by Django 5.0.1 on 2024-02-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tasks_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor')),
            ],
        ),
    ]
