# Generated by Django 5.0.1 on 2024-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='ABC123', max_length=7, unique=True),
        ),
    ]
