# Generated by Django 5.0.1 on 2024-02-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_project_supervisor_project_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
